# Week 4

## Birthday Paradox

In [1]:
import random

l=[]

for i in range(30):
    l.append(random.randint(1,365))
l.sort()
print(l)
i=0
flag=0 #denotes there is no repititions

while (i < len(l)-1):
    if (l[i] == l[i+1]):
        print("Repeats", l[i], l[i+1] )
        flag = 1 
    i=i+1
if (flag == 0):
    print('No repetitions')

[3, 31, 37, 80, 105, 109, 125, 135, 142, 152, 154, 189, 200, 219, 231, 239, 253, 257, 264, 269, 276, 288, 291, 301, 333, 339, 340, 342, 342, 353]
Repeats 342 342


## The obvious sort

In [4]:
l = [12,10,7,18,6,42,8,5,45,5,214,325,54,2,42,4,7]
x=[]

while (len(l)>0):
    min=l[0]
    for i in range(len(l)):
        if (l[i]<min):
            min=l[i]
    x.append(min)
    l.remove(min)
print(l,x)

[] [2, 4, 5, 5, 6, 7, 7, 8, 10, 12, 18, 42, 42, 45, 54, 214, 325]


## Dot product
write a piece of code to find dot product of two vectors

In [5]:
import random

x = random.sample(list(range(10)),5)
y = random.sample(list(range(10)),5)

sum = 0
for i in range(len(x)):
    sum = sum + x[i]*y[i]
print(x, y, sum) #if lists are of different lengths, this wont work

[0, 8, 6, 3, 2] [5, 1, 3, 4, 9] 56


## Matrix addition

In [6]:
dim =3

r1= [1,2,3]
r2= [4,5,6]
r3= [7,8,9]

s1= [1,2,1]
s2= [4,5,6]
s3= [4,3,6]

A=[]
A.append(r1)
A.append(r2)
A.append(r3)

B=[]
B.append(s1)
B.append(s2)
B.append(s3)

C = [[0,0,0],[0,0,0],[0,0,0]]
for i in range(dim):
    for j in range(dim):
        C[i][j] = A[i][j] + B[i][j]
print(A)
print(B)
print(C)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
[[1, 2, 1], [4, 5, 6], [4, 3, 6]]
[[2, 4, 4], [8, 10, 12], [11, 11, 15]]


## Matrix Multiplication

In [7]:
# using loops

A=[[1,2,3],[1,2,3],[1,2,3]]
B=[[1,2,3],[1,2,3],[1,2,3]]
C=[[0,0,0],[0,0,0],[0,0,0]]
dim=3

for i in range(dim):
    for j in range(dim):
        for n in range(dim):
            C[i][j] = C[i][j] + (A[i][n] * B[n][j])
print(C)


# using numpy matrix multiplication

import numpy
A=[[1,2,3],[1,2,3],[1,2,3]]
B=[[1,2,3],[1,2,3],[1,2,3]]
X = numpy.mat(A)
Y = numpy.mat(B)
print(X*Y)

[[6, 12, 18], [6, 12, 18], [6, 12, 18]]
[[ 6 12 18]
 [ 6 12 18]
 [ 6 12 18]]
